### ISSUE TITLE
Total number of stars for the project is 0

### ISSUE THREAD

**Issue by KarolPiechoczek** [Unpublished/GithubTrending#43]
In the second week in JSON, the number of stars is equal to 0 for each project. For example:

`{"description": "GitHub Actions runner images", "language": "PowerShell", "repo": "runner-images", "new_stars": 77, "stars": 0, "owner": "actions", "forks": 0},
{"description": "Open-source end-to-end LLM Development Platform", "language": "Python", "repo": "opik", "new_stars": 210, "stars": 0, "owner": "comet-ml", "forks": 0},
{"description": "Firefly III: a personal finances manager", "language": "PHP", "repo": "firefly-iii", "new_stars": 123, "stars": 0, "owner": "firefly-iii", "forks": 0}
]`

The new stars are correct, but the total number of stars is “0”:

 "new_stars": 123, "stars": 0

**Comment by Unpublished** [comment]
Thanks for bringing this to attention @KarolPiechoczek, fixed the scraping via #44 (together with forks count)
